# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a032d076815cee2ea2153bb844f7c519e03c6cb29eb38e71df5681a2f843506e4c2a9ada5940a1066f64ff4296f2df3f0394c6b382ba918fcaa807fcc4e3de0c

test:
  secret_key_base: 59d5a4391b9d436260e1949002bfe43080fe86032c40de653f66018a01099b0159b0f584321e201492c67a9aac8695cf47c7e387febd8444f67f519cf5dbcf48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
